<?php

return [
    'users' => [
        'id' => 'int',
        'name' => 'varchar(100)',
        'username' => 'varchar(100)',
        'email' => 'varchar(100)',
        'verified' => 'tinyint',
        'password' => 'varchar(100)',
        'created_at' => 'datetime',
        'admin' => 'tinyint',
    ],
    'discussions' => [
        'id' => 'int',
        'group_id' => 'int',
        'user_id' => 'int',
        'status' => 'int',
        'name' => 'varchar(100)',
        'body' => 'text',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
        'total_comments' => 'int',
    ],
    'posts' => [
        'id' => 'int',
        'discussion_id' => 'int',
        'user_id' => 'int',
        'body' => 'text',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ],
    'tags' => [
        'id' => 'int',
        'name' => 'varchar(100)',
        'slug' => 'varchar(100)',
        'description' => 'text',
        'parent_id' => 'int',
        'position' => 'int',
        'discussion_count' => 'int',
        'is_hidden' => 'tinyint',
        'is_restricted' => 'tinyint',
    ],
    'groups' => [
        'id' => 'int',
        'name' => 'varchar(100)',
        'body' => 'text',
    ],
    'membership' => [
        'user_id' => 'int',
        'group_id' => 'int',
    ],
    'files' => [
        'id' => 'int',
        'parent_id' => 'int',
        'group_id' => 'int',
        'user_id' => 'int',
        'item_type' => 'int',
        'filesize' => 'int',
        'status' => 'int',
        'name' => 'varchar(100)',
        'mime' => 'varchar(100)',
        'path' => 'text',
        'original_filename' => 'text',
        'original_extension' => 'text',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ],
    'reactions' => [
        'id' => 'int',
        'user_id' => 'int',
        'reactable_id' => 'int',
        'reactable_type' => 'varchar(100)',
        'type' => 'varchar(100)',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ],
];
