<?php

return [
    'users' => [
        'id' => 'int4',
        'username' => 'varchar(60)',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'name' => 'varchar',
        'last_posted_at' => 'timestamp',
        'active' => 'bool',
        'username_lower' => 'varchar(60)',
        'last_seen_at' => 'timestamp',
        'admin' => 'bool',
        'approved' => 'bool',
        'trust_level' => 'int4',
        'approved_by_id' => 'int',
        'approved_at' => 'timestamp',
        'first_seen_at' => 'timestamp',
    ],
    'topics' => [
        'id' => 'int4',
        'title' => 'varchar',
        'last_posted_at' => 'timestamp',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'views' => 'int4',
        'posts_count' => 'int4',
        'user_id' => 'int4',
        'last_post_user_id' => 'int4',
        'highest_post_number' => 'int4',
        'category_id' => 'int',
        'closed' => 'bool',
        'archived' => 'bool',
        'pinned_at' => 'timestamp',
        'slug' => 'varchar',
        'fancy_title' => 'varchar',
        'pinned_globally' => 'bool',
    ],
    'posts' => [
        'id' => 'int4',
        'user_id' => 'int4',
        'topic_id' => 'int4',
        'post_number' => 'int4',
        'raw' => 'text',
        'cooked' => 'text',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'reply_to_post_number' => 'int4',
        'deleted_at' => 'timestamp',
        'score' => 'float8',
        'post_type' => 'tinyint',
        'sort_order' => 'int4',
        'user_deleted' => 'bool',
        'cook_method' => 'int4', // 1
    ],
    'categories' => [
        'id' => 'int4',
        'name' => 'varchar',
        'topic_id' => 'int4',
        'parent_category_id' => 'int4',
        'topic_count' => 'int',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'user_id' => 'int4',
        'slug' => 'varchar',
        'description' => 'text',
        'post_count' => 'int4',
        'latest_post_id' => 'int4',
        'latest_topic_id' => 'int4',
        'position' => 'int4',
        'sort_order' => 'int4',
        'emoji' => 'varchar',
    ],
    'groups' => [
        'id' => 'int4',
        'name' => 'varchar',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'user_count' => 'int4',
        'full_name' => 'varchar',
        'visibility_level' => 'int4',
    ],
    'group_users' => [
        'user_id' => 'int4',
        'group_id' => 'int4',
    ],
    'uploads' => [
        'id' => 'int4',
        'user_id' => 'int4',
        'original_filename' => 'varchar',
        'filesize' => 'int8',
        'width' => 'int4',
        'height' => 'int4',
        'url' => 'varchar',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
        'sha1' => 'varchar(40)',
        'origin' => 'varchar(2000)',
        'extension' => 'varchar(10)',
        'animated' => 'bool',
    ],
    'discourse_reactions_reactions' => [
        'id' => 'int4',
        'user_id' => 'int4',
        'post_id' => 'int4',
        'reaction_type' => 'int4',
        'reaction_value' => 'varchar',
        'reaction_users_count' => 'int',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
    ],
    'reaction_user' => [
        'id' => 'int4',
        'user_id' => 'int4',
        'post_id' => 'int4',
        'reaction_id' => 'int4',
        'created_at' => 'timestamp',
        'updated_at' => 'timestamp',
    ],
];
