<?php

/** Defines database schema for Source\Xenforo. */

return [
    'attachment' => [
        'attachment_id' => 'int',
        'filename' => 'text',
        'file_size' => 'int',
        'user_id' => 'int',
        'upload_date' => 'datetime',
        'width' => 'int',
        'height' => 'int',
        'data_id' => 'int',
        'content_type' => 'varchar(200)',
        'content_id' => 'int',
    ],
    'attachment_data' => [
        'filename' => 'text',
        'file_size' => 'int',
        'user_id' => 'int',
        'width' => 'int',
        'height' => 'int',
        'upload_date' => 'datetime',
        'data_id' => 'int',
        'file_key' => 'varchar(200)',
    ],
    'conversation_master' => [
        'conversation_id' => 'int',
        'title' => 'text',
        'user_id' => 'int',
        'start_date' => 'datetime',
    ],
    'conversation_message' => [
        'message_id' => 'int',
        'conversation_id' => 'int',
        'message_date' => 'datetime',
        'user_id' => 'int',
        'message' => 'text',
    ],
    'conversation_recipient' => [
        'conversation_id' => 'int',
        'user_id' => 'int',
        'deleted' => 'tinyint',
        'recipient_state' => 'tinyint',
    ],
    'conversation_user' => [
        'conversation_id' => 'int',
        'owner_user_id' => 'int',
    ],
    'node' => [
        'node_id' => 'int',
        'title' => 'varchar(200)',
        'description' => 'text',
        'parent_node_id' => 'int',
        'display_order' => 'int',
        'display_in_list' => 'tinyint',
    ],
    'post' => [
        'message' => 'text',
        'post_id' => 'int',
        'thread_id' => 'int',
        'user_id' => 'int',
        'post_date' => 'datetime',
        'message_state' => 'varchar(200)',
    ],
    'thread' => [
        'thread_id' => 'int',
        'node_id' => 'int',
        'title' => 'text',
        'reply_count' => 'int',
        'view_count' => 'int',
        'user_id' => 'int',
        'post_date' => 'datetime',
        'sticky' => 'tinyint',
        'discussion_open' => 'tinyint',
        'last_post_date' => 'datetime',
        'first_post_id' => 'int',
    ],
    'user' => [
        'user_id' => 'int',
        'username' => 'varchar(200)',
        'email' => 'varchar(200)',
        'custom_title' => 'varchar(200)',
        'register_date' => 'datetime',
        'last_activity' => 'datetime',
        'is_admin' => 'tinyint',
        'is_banned' => 'tinyint',
        'data' => 'text',
        'avatar' => 'varchar(200)',
        'avatar_date' => 'datetime',
        'user_group_id' => 'int',
        'secondary_group_ids' => 'varchar(200)',
    ],
    'user_authenticate' => [
        'user_id' => 'int',
    ],
    'user_group' => [
        'user_id' => 'int',
        'user_group_id' => 'int',
        'title' => 'varchar(200)',
    ],
    'user_profile' => [
        'user_id' => 'int',
        'signature' => 'text',
    ],
];
